const bodyParser = require("body-parser");
const express = require("express");
const app = express();
var pdf = require('html-pdf');
var randomstring = require("randomstring");

app.use(bodyParser.urlencoded({ extended: false }));

app.post('/api/v1/create', (req, res) => {

	console.log(req.body.image)

	var rand = randomstring.generate(7);
// console.log(req.body);
	html = "<html><body><h1>FrontRx</h1><br><br>" +
		"<img src='http://api.qrserver.com/v1/create-qr-code/?color=000000&bgcolor=FFFFFF&data=frontrx%3A%2F%2F" +
		rand + "&qzone=4&margin=0&size=200x200&ecc=L'/><br><br>" +
		"<strong>Prescribed Name:</strong> " + req.body.name +
		"<br>" +
		"<strong>Prescribed Mobile:</strong> " + req.body.phone +
		"<br><br>" +
		"<div style='text-align: center;'><img alt='' src='http://localhost/node/aaa.jpg' /></div> "+
		"<br><br>" +
		"<embed src='http://localhost/pdf/dir/test-DofToB6.pdf' type='application/pdf' width='100%' height='600px' />"+
		'<object data="http://localhost/pdf/dir/test-DofToB6.pdf" type="application/pdf" width="100%" height="800px">'+
 			"<p>It appears you don't have a PDF plugin for this browser</p>"+
		"</object>"+
		"<br>" +
		"<br><br><br>" +
		"<h2>Present this file to your pharmacist</h2>" +
		"<br><br>Generated by https://frontrx.com<br><br></html>";

	var filepath = './dir/test-'+rand+'.pdf', file = '';

	pdf.create(html).toFile(filepath, function(er, str) {
	  	console.log(str.filename);
	  	file = str.filename;
	});
  	console.log(file)
});

app.listen(3000, () => {
  	console.log("Started on http://localhost:3000");
});